# Generated by Django 6.0.2 on 2026-02-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_alter_question_difficulty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='feedback',
            new_name='improvement',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='strengths',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='weaknesses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
