# Generated by Django 6.0.2 on 2026-02-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_rename_feedback_answer_improvement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewsession',
            name='end_time',
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='tech_stack',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='overall_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='role',
            field=models.CharField(max_length=50),
        ),
    ]
